### ISSUE TITLE
FB login not working

### ISSUE THREAD

**Issue by cutugno** [darkwhispering/facebook-sdk-codeigniter#13]
Hi, I'm using version 2.0.0 of your library on codeigniter 3, it worked great until a couple of days ago, when it suddenly broke. Clicking on the FB login button now returns an empty page.

I made some debugging and I found that in FacebookRedirectLoginHelper.php, the function "isValidRedirect" returns false, even if both GET variables are set in url and present in CI benchmark.

 if (!$this->getCode() || !isset($_GET['state'])) {
      log_message (LOG,'FB login problem getCode: "'.$this->getCode().'" (login/fblogin)',LOGPREFIX);	
      return false;
}
log entry for this --> DEBUG - 2015-12-11 11:31:20 -->FB login problem getCode: "" (login/fblogin)
getCode() returns null

**Comment by darkwhispering** [comment]
@cutugno I have to inform you that I have decided to drop support for v2.0.0 of my library as it is using an outdated version of the Facebook PHP SDK.

I highly recommend that you update to the new v3.0.0 and Facebook PHP SDK v5
