### ISSUE TITLE
Call to a member function isExpired() on a non-object

### ISSUE THREAD

**Issue by Odepia** [darkwhispering/facebook-sdk-codeigniter#22]
Hi,

I have the following issue when a user click on the "Cancel" button when the Facebook authentication page is shown up.

> A PHP Error was encountered
Severity: Error
Message: Call to a member function isExpired() on a non-object
Filename: libraries/Facebook.php
Line Number: 105
Backtrace:

I use the latest Dev version of Facebook PHP SDK v5 (3.0.0-beta2)

**Comment by Odepia** [comment]
Here is the way I fixed the issue (not sure that's the good one, but it works):

I replace the following function by the next one:

`    public function is_authenticated() {

        // authenticate user
        $access_token = $this->authenticate();

        if (isset($access_token) && !$access_token->isExpired()) {
            return $access_token;
        }

        return null;
    }`


`    public function is_authenticated() {

        // get the current access token if exist
        $access_token = $this->get_access_token();

        if (isset($access_token) && !$access_token->isExpired()) {
            return $access_token;
        }

        return null;
    }`

**Comment by ongpang** [comment]
Hi Bro. For me, not working.

**Comment by darkwhispering** [comment]
@Odepia @ongpang I have just released a new version of the library, that is now in master branch. IT includes a rewrite in how a access token is validated. I highly recommend to update.
