### ISSUE TITLE
Sessions are not active

### ISSUE THREAD

**Issue by andrefrcastro** [darkwhispering/facebook-sdk-codeigniter#27]
Any thoughts on how solve the Sessions are not active issue?

> Fatal error: Uncaught exception 'Facebook\Exceptions\FacebookSDKException' with message 'Sessions are not active. Please make sure session_start() is at the top of your script.' in /application/third_party/facebook-php-sdk/src/Facebook/PersistentData/FacebookSessionPersistentDataHandler.php on line 50

Extending the `FacebookRedirectLoginHelper` no longer works on the new SDK.

**Comment by darkwhispering** [comment]
Not at the moment. I have so far been unable to replicate this issue myself, but I have also not had time to do any extensive testing yet.

I'll update as soon as I have something more.

If you find a solution yourself in the meantime, please share here.

**Comment by darkwhispering** [comment]
I have so far still been unable to replicate the exact issue. I have however just released a new version that includes multiple changes and modifications that I hope might solve your issues.

Please update and let me know if you continue to run into any issues.
