### ISSUE TITLE
The redirect_uri URL must be absolute

### ISSUE THREAD

**Issue by eotg1910** [darkwhispering/facebook-sdk-codeigniter#29]
i have a problem with your code 
https://www.facebook.com/v2.6/dialog/oauth?client_id=appid&state=appsecret&response_type=code&sdk=php-sdk-5.2.0&redirect_uri=www.mywebsite.com%2FCodeigniter%2F%2Findex.php%2Fpage&scope=public_profile%2Cpublish_actions%2Cemail

**Comment by tonirilix** [comment]
You're missing the protocol before the uri. "http://www.mywebsite.com".

But actually I don't know why it's not there since the code for that is as follows:

`
return $this->helper->getLoginUrl(
            base_url() . $this->config->item('facebook_login_redirect_url'),
            $this->config->item('facebook_permissions')
        );
`
which should already put the protocol.

**Comment by darkwhispering** [comment]
@eotg1910 As mentioned by @tonirilix the URL should be set correctly by the `base_url()` helper in the library. However, the `base_url()` set what value you have set in your configuration file. What value do you have set for `$config['base_url']` in your config?

Also, what version of the library are you using. Latest v3.0.0 or the older v2?
