### ISSUE TITLE
A question, 5.0.0

### ISSUE THREAD

**Issue by ivantcholakov** [darkwhispering/facebook-sdk-codeigniter#3]
I can see that facebook/php-sdk-v4 has a new major version 5.0.0. Is this new version compatible with your library?

**Comment by darkwhispering** [comment]
I have not tested v5 yet so I do not know.

**Comment by darkwhispering** [comment]
I have done a first quick read of the new 5.0 SDK and can for sure say that my library will not work with this SDK.

I complete rewrite will be needed to update my library as version 5.0 brought many breaking changes.

At this point I do not have a timeline when and update of my library will be available.

**Comment by eduhakim** [comment]
hii darkwhispering ..
I try your library  but I find trouble, may be I dont understand how to instalation your library in point no 3 that "In CodeIgniter /application/config/config.php, configure the Session Variables." or point no 5 ..
I have setting /application/config/facebook.php with my facebook app id and facebook app secret ..

I found message eror report like this " Message: Class 'Facebook\FacebookSession' not found "
![eror fb](https://cloud.githubusercontent.com/assets/13493474/8888213/8dcb715c-32ce-11e5-84f7-cf8e55e7ca40.PNG)

If you know this solution, please explain to me ..
Thanks

**Comment by bsimser** [comment]
Just did an update to the SDK and yeah, it's not going to work at all. The new FB SDK is all namespaced differently (e.g. the GraphObject is now Facebook\GraphNodes\GraphObject) and classes have been removed (there is no more FacebookSession class) with those methods folded into things like the Facebook\Facebook class.

I've been doing FB development for 7 or 8 years now and every SDK breaks the previous one so this is typical (in true Facebook fashion they still call the SDK v4 but it's 5.0.0 internally)

I really like the classes and approach you have here so going to fork this and try to rebuild it with v5 (following the same structure as it's easy and clean and works well with CI).

**Comment by darkwhispering** [comment]
Yeah, not uncommon that the next version of something from Facebook breaks the previous completely.

I have started developing and update of my library, but not yet publish the branch here. I could do that if you would like to contribute to that directly instead. Let me know.

**Comment by bsimser** [comment]
Sure, I spent about 30 minutes on it tonight but the whole session/token thing is a PITA. If you have a dev branch I'll gladly start from it and work off it instead.

**Comment by darkwhispering** [comment]
I'll publish the develop branch during my day today and update there when it is available.

**Comment by bsimser** [comment]
Sounds great, thanks!

**Comment by darkwhispering** [comment]
Sry for the delay. I have now published the develop branch, https://github.com/darkwhispering/facebook-sdk-v4-codeigniter/tree/fb-sdk-v5-develop

I have already done a lot of work, and it includes an almost complete rewrite of the library. If you go to `your-domain.com/example` and select the JS example you can login and post to your Facebook wall already.

The main difference from the old version is that I removed all the unique functions to get user info, post to wall and so on and made on function that accept any Facebook Graph request.

For example
```php
// Get logged in user info
$user = $this->facebook->request('get', '/me')
var_dump($user)

// Post to wall
$result = $this->facebook->request('post', '/me/feed', array('message' => $this->input->post('message')));
var_dump($result);
```

There is also the option to get the [Facebook\Facebook Object](https://developers.facebook.com/docs/php/Facebook/5.0.0#overview) and do what ever you want yourself.


```php
$fb = $this->facebook->object()

// Get logged in user info
$response = $fb->get('/me'); // you should do a try, catch here
$user = $response->getGraphUser();
var_dump($user);
```

**Comment by dreammonkey** [comment]
hey  darkwispering !
I've tried your dev branch (great work!) but I'm unable to get an active session in php (using the javascript helper) However I'm able to get user data / access token through the javascript sdk...

I'm using v2.4 of the api, with the cookie:true option.

Currently I'm getting an SDK Exception when trying to call $helper->getAccessToken():
[FACEBOOK PHP SDK authenticate] code: 2500 | message: Unknown path components: /oauth/access_token

Have you tried to get an acces_token with the use of the javascript helper alone ? (i.e. not using the redirect helper) ?

Somehow I believe it's a problem with the SDK, not with your implementation...

Looking forward to your thoughts, because I'm starting to get an headache here ;)

**Comment by dreammonkey** [comment]
no one has seen this problem? has anyone tested the js helper ?
thanks for you reply

**Comment by darkwhispering** [comment]
@dreammonkey I have been very busy lately and support for FB SDK v5 is very much experimental at this point. I have yet myself to test all scenarios with JS SDK login and so on.

I do not have a timeframe yet as of when I will have full support for v5.

**Comment by darkwhispering** [comment]
Hi again,

I have spent a fee hours today and fixes some issue and tested both web redirect and Javascript SDK based login flows without any issues.

You can find the latest code here: https://github.com/darkwhispering/facebook-sdk-v4-codeigniter/tree/fb-sdk-v5-develop

Let me know if you run into any issues of not.

**Comment by dreammonkey** [comment]
hi @darkwhispering and for all those concerned,

The problem I encountered was when specifying the graph API version I forgot to prepend 'v' to the config array of the Facebook SDK.

The SDK itself never complained about it, which I think it actually should...
So the bottom line is: don't forget to specify 'v2.4' in stead of  just '2.4' ... ;)

**Comment by darkwhispering** [comment]
@dreammonkey I have update the comments in the config file with an example of Graph variable value to minimize the risk of missing the `v` in front.

**Comment by darkwhispering** [comment]
Support for Facebook PHP SDK v5 has been merged to master and is considered stable enough for use.

**Comment by ivantcholakov** [comment]
Thank you. I will try it soon.
