### ISSUE TITLE
i had error

### ISSUE THREAD

**Issue by sarunas1992** [darkwhispering/facebook-sdk-codeigniter#30]
Fatal error: Class 'Facebook\Facebook' not found in F:\wamp\www\demo\application\libraries\Facebook.php on line 67

p.s. i dont use composer.

**Comment by renjinsk** [comment]
You should then. Thats the fastest way to resolve your "issue"

**Comment by darkwhispering** [comment]
Hi @sarunas1992 

My library requires the Facebook SDK to be installed with Composer, it is clearly stated in the installation steps.

Other ways of installing the SDK is unsupported.

Install the SDK using composer and make sure that CI autoloads the Composer autoloader will solve your issue.
