### ISSUE TITLE
web_login?code=XXXX

### ISSUE THREAD

**Issue by mgjuhler** [darkwhispering/facebook-sdk-codeigniter#33]
When using the web_login in the examples and my app info in the config file it "works" or at least a part of it is. When clicking the "login" button  i get redirected back to `http://www.mcww.com/web_login?code=XXXXX` and nothing more happens, what am i doing wrong?

Info
- php: 5.6.24
- composer: (latest)
- facebook php sdk: 5.2.0
- codeigniter: 3.0.6
- codeigniter session: on

**Comment by mgjuhler** [comment]
bump!?

**Comment by darkwhispering** [comment]
@mgjuhler Have you made sure you have sessions configured correctly in CI? It's required for the web login flow to work correctly.

If you do have sessions configured. Do you have any errors in your server logs?

**Comment by mgjuhler** [comment]
session is working, i am using it for my normal login system.

here is the log from codeigniter:
`ERROR - 15/08/2016 19:45:17 --> [FACEBOOK PHP SDK] code: 0 | message: Cross-site request forgery validation failed. Required param "state" missing from persistent data.

ERROR - 15/08/2016 19:45:17 --> [FACEBOOK PHP SDK] code: 0 | message: Cross-site request forgery validation failed. Required param "state" missing from persistent data.`

**Comment by mgjuhler** [comment]
ops... sorry for closing

**Comment by darkwhispering** [comment]
The issue has to do with the session not working properly. I don't know exactly what it could be, it most likely depends on how you have your sessions setup.

Maybe this post can help you? http://stackoverflow.com/a/34361172
