### ISSUE TITLE
Can't Load URL in Facebook App 

### ISSUE THREAD

**Issue by sonha** [darkwhispering/facebook-sdk-codeigniter#37]
"Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings."
Can you help me ? 
![demo1](https://cloud.githubusercontent.com/assets/2588290/18270265/3fa0c67e-7456-11e6-88f8-fb5e471bd58f.png)
![demo2](https://cloud.githubusercontent.com/assets/2588290/18270275/4871302c-7456-11e6-9fcc-ab8b187a3542.png)
![demo3](https://cloud.githubusercontent.com/assets/2588290/18270285/50002cee-7456-11e6-8b75-acc27617cb84.png)
This is my Facebook.php file : 
![demo4](https://cloud.githubusercontent.com/assets/2588290/18270306/670ad7fe-7456-11e6-993d-49835ff44879.png)

**Comment by sonha** [comment]
http://image.prntscr.com/image/d3ea9b02cc7546bc8e3833f0b2bdd9eb.png

**Comment by sonha** [comment]
I solved this problem( base_url error)
![fbtool](https://cloud.githubusercontent.com/assets/2588290/18338141/ccb16378-75c0-11e6-97e1-f18aaeda372a.png).
Thank you !

**Comment by the-cool-man** [comment]
Set No : Use Strict Mode for Redirect URIs 
![fb](https://user-images.githubusercontent.com/20378744/31489694-251191ea-af5f-11e7-86fa-8a6cb504b308.png)
