### ISSUE TITLE
could you please make an example for upload photo and video ? 

### ISSUE THREAD

**Issue by minamagdy666** [darkwhispering/facebook-sdk-codeigniter#40]
I tried to make a function for photo and video but did not get success, what is wrong here ?

`public function post_media()
	{
		header('Content-Type: application/json');
		$result = $this->facebook->user_upload_request(
			'post',
			'/me/photos',
			['url' => $this->input->post('file_img')]
		);
		echo json_encode($result);
	}`

**Comment by darkwhispering** [comment]
@minamagdy666 sry for late reply.

You are using the method incorrectly. The upload method does not take the same parameters as the regular `request()` method.

As detailed in the [documentation](https://github.com/darkwhispering/facebook-sdk-codeigniter/tree/master#user_upload_requeststring-path_to_file--array-params--string-type--string-access_token) the `user_upload_request()` method takes

1.  string $path_to_file (required)
2. array $params (optional)
3. string $type (optional)
4. string $access_token (optional)

Example
```php
$this->facebook->user_upload_request('/path/to/file.jpg', ['message' => 'This is a test upload']);
```
