### ISSUE TITLE
Login doens't work with Strict URI Matching

### ISSUE THREAD

**Issue by AsoStrife** [darkwhispering/facebook-sdk-codeigniter#54]
Using this library all work ok. 
But enabling Strict URI Matching (oAuth settings) the login doesn't work. 
Still return on the login page without access token.

**Comment by kimho** [comment]
I figured it out.
Update facebook package and it fixes the problem.
`composer update facebook/graph-sdk`

**Comment by AsoStrife** [comment]
Yes me too. Need to update the sdk with the newest version. 
Close.
